{
    'name': 'Helpdek ruben Seijas',
    'summary': 'Manage helpdesk tickets',
    'version': '15.0.1.0.0',
    'author': 'Ruben Seijs',
    'depends': ['base', 'mail'],
    'license': 'AGPL-3',
    'data': [
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'wizards/create_ticket_views.xml',
        'views/helpdesk_ticket_action_views.xml',
        'views/helpdesk_ticket_tag_views.xml',
        'views/helpdesk_ticket_views.xml',
        'reports/ticket_report_templates.xml',
        'reports/partner_card_report_template.xml',
        'reports/ticket_report.xml',
        'reports/partner_report.xml',
        'demo/helpdesk_demo.xml',
        'data/ir_cron.xml',
    ],
    'demo': [
        'demo/helpdesk_demo.xml',
    ],
} 